"""created User, BookCopy and BookRequest models and relationships

Revision ID: 58d68b0acf4a
Revises: 6fffd5d1c9a8
Create Date: 2026-02-25 11:52:25.855340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d68b0acf4a'
down_revision = '6fffd5d1c9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('book_copies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_book_copies_owner_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('book_copy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_copy_id'], ['book_copies.id'], name=op.f('fk_book_requests_book_copy_id_book_copies')),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_book_requests_requester_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_requests')
    op.drop_table('book_copies')
    op.drop_table('users')
    # ### end Alembic commands ###
