"""added image column to BookCopy

Revision ID: 90541a285bda
Revises: 58d68b0acf4a
Create Date: 2026-02-25 12:04:44.155655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90541a285bda'
down_revision = '58d68b0acf4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_copies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_copies', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
